### ISSUE TITLE
PEER-Rochester schedule

### ISSUE THREAD

**Issue by kustuschmb** [SayreLab/peerwebsite#16]
I just pulled up the PEER-Rochester website and noticed that the schedule is not loading.

**Comment by HaimarR** [comment]
Found the issue. On the FS Spreadsheet the name of the page was "Rochester2024" instead of "Rochester 2024" (the space between Rochester and 2024 was missing). The code was looking for a page called "Rochester 2024" but couldn't find it due to the naming error on the spreadsheet. I have fixed the name on the spreadsheet and it should work now. I will mark it as completed, reopen the issue if there's anything wrong.
